"""Hex-head bolt: an ISO 4014/4017-style hex head plus a cylindrical shank with a
modeled external ISO metric thread.

The shank thread is generated by the shared thread engine (``app.cad.threads``);
short shanks are modeled (real helical geometry in STL + STEP), long shanks fall
back to a clean chamfered cylinder marked as cosmetic and the geometry audit
reconciles the representation. The hex head across-flats follows the standard
table for the nominal size.

LEGAL / SOURCING NOTE:
Generated by LunaiCAD's own parametric engine from public ISO metric data.
McMaster CAD files must not be scraped, cached, redistributed, or used as source
geometry unless LunaiCAD has explicit commercial permission.
"""
from __future__ import annotations

import math

import cadquery as cq

from app.cad.base import BaseTemplate, CadGenerationError, DimensionSpec
from app.schemas.design_spec import DesignSpec

_COS30 = math.cos(math.pi / 6.0)

# ISO 4014/4017 hex-head across-flats (s) and head height (k), mm, by nominal Ø.
HEX_HEAD: dict[float, dict[str, float]] = {
    3.0: {"s": 5.5, "k": 2.0}, 4.0: {"s": 7.0, "k": 2.8}, 5.0: {"s": 8.0, "k": 3.5},
    6.0: {"s": 10.0, "k": 4.0}, 8.0: {"s": 13.0, "k": 5.3}, 10.0: {"s": 16.0, "k": 6.4},
    12.0: {"s": 18.0, "k": 7.5}, 14.0: {"s": 21.0, "k": 8.8}, 16.0: {"s": 24.0, "k": 10.0},
    20.0: {"s": 30.0, "k": 12.5}, 24.0: {"s": 36.0, "k": 15.0},
}


def hex_head_dims(nominal: float) -> dict[str, float]:
    row = HEX_HEAD.get(round(nominal, 3))
    if row:
        return row
    return {"s": round(1.5 * nominal, 1), "k": round(0.65 * nominal, 1)}


class BoltTemplate(BaseTemplate):
    object_type = "bolt"
    name = "Hex-head Bolt"
    description = "Hex head + externally-threaded shank (ISO metric)."
    dimensions = [
        DimensionSpec("thread_major_diameter", "Nominal (major) diameter", 12.0, 2.0, 48.0),
        DimensionSpec("thread_pitch", "Thread pitch", 1.75, 0.2, 6.0),
        DimensionSpec("length", "Shank length (under head)", 20.0, 4.0, 400.0),
        # Threaded portion at the far end; 0 = fully threaded (defaults to length).
        DimensionSpec("threaded_length", "Threaded length", 0.0, 0.0, 400.0),
        DimensionSpec("head_across_flats", "Hex-head across flats", 18.0, 3.0, 90.0),
        DimensionSpec("head_height", "Hex-head height", 7.5, 1.0, 60.0),
    ]

    def build(self, spec: DesignSpec) -> "cq.Workplane":
        from app.cad.threads import make_external_thread_rod
        from app.config import settings

        r = self.resolve(spec)
        major = r["thread_major_diameter"]
        pitch = r["thread_pitch"]
        length = r["length"]
        threaded_length = r.dims_mm.get("threaded_length", 0.0) or length
        threaded_length = min(threaded_length, length)
        s = r["head_across_flats"]
        k = r["head_height"]
        rmaj = major / 2.0
        if s <= major:
            raise CadGenerationError(
                f"bolt head across-flats ({s}mm) must exceed the shank diameter ({major}mm)")

        detail = getattr(settings, "thread_detail", "modeled") or "modeled"

        # Build additively: the threaded section is a real swept-ridge thread (the
        # OCC helical CUT silently no-ops past a few turns, so the thread is fused
        # onto a minor-diameter core, never cut). The unthreaded shank then overlaps
        # down into the thread, fused 0.1 mm PROUD of the crest: a flush/coincident
        # shank wall would sit tangent to the helical crest (degenerate faces ⇒
        # non-manifold), whereas this tiny thread-relief shoulder fuses watertight.
        body, _res = make_external_thread_rod(
            major_diameter=major, pitch=pitch, length=threaded_length,
            detail=detail, chamfer_ends=False)

        # Unthreaded plain shank between the thread and the head.
        plain_len = length - threaded_length
        if plain_len > 0.05:
            overlap = min(0.6, threaded_length * 0.5)
            plain = (cq.Workplane("XY").workplane(offset=threaded_length - overlap)
                     .circle(rmaj + 0.1).extrude(plain_len + overlap))
            body = cq.Workplane(obj=body.val().fuse(plain.val(), tol=1e-6).clean())

        # Hex head on top of the shank (z = length .. length+k), chamfered top. The
        # head is wider than the shank, so it fuses cleanly onto the flat top face.
        head = (cq.Workplane("XY").workplane(offset=length)
                .polygon(6, s / _COS30).extrude(k))
        head_chamfer = min((s / _COS30 - s) / 2.0 * 0.85, k * 0.2)
        if head_chamfer > 0.05:
            try:
                head = head.faces(">Z").chamfer(head_chamfer)
            except Exception:  # noqa: BLE001 — cosmetic head chamfer
                pass

        return cq.Workplane(obj=body.val().fuse(head.val(), tol=1e-6).clean())
