"""Rigid shaft coupler: a cylindrical body with two coaxial bores (one per shaft,
stepped at the middle) and radial set-screw holes.

Set-screw holes are real threaded SEATS, not plain clearance holes: each radial
hole is cut at the ISO tap-drill (minor) diameter and given cosmetic thread-relief
ring grooves out to the major diameter, so the thread is visibly represented in the
geometry. A fully MODELED helical internal thread on these small radial holes (M4
×0.7 / M5 ×0.8 through a curved wall into a curved bore) is too fragile to validate
watertight, so the representation is honestly marked COSMETIC and the part ships
REVIEW (never a PASS that implies a validated thread fit).

Placement (``placement_strategy = "two_axial_stations_opposing"``): the holes are
split between two axial stations — one over each shaft bore — and distributed evenly
around the circumference at each station, with the stations offset 90° for a clean,
symmetric layout that never collides.

LEGAL / SOURCING NOTE:
Generated by LunaiCAD's own parametric engine. McMaster CAD files must not be
scraped, cached, redistributed, or used as source geometry unless LunaiCAD has
explicit commercial permission.
"""
from __future__ import annotations

import math

import cadquery as cq
from cadquery import Vector

from app.cad.base import BaseTemplate, CadGenerationError, DimensionSpec
from app.schemas.design_spec import DesignSpec

# ISO metric coarse pitch (mm) for common set-screw sizes.
SET_SCREW_PITCH = {3.0: 0.5, 4.0: 0.7, 5.0: 0.8, 6.0: 1.0, 8.0: 1.25}
# ISO tap-drill (thread core / minor) diameter (mm) by nominal size — the correct
# hole to cut before tapping an internal thread.
SET_SCREW_TAP_DRILL = {3.0: 2.5, 4.0: 3.3, 5.0: 4.2, 6.0: 5.0, 8.0: 6.8}

PLACEMENT_STRATEGY = "two_axial_stations_opposing"


def set_screw_pitch(nominal: float) -> float:
    return SET_SCREW_PITCH.get(round(nominal, 3), round(nominal * 0.15, 2))


def set_screw_tap_drill(nominal: float) -> float:
    return SET_SCREW_TAP_DRILL.get(round(nominal, 3), round(nominal * 0.8, 1))


def set_screw_hole_positions(count: int, length: float) -> list[tuple[float, float]]:
    """Deterministic (z, angle_deg) for each radial set-screw hole.

    Two axial stations (one over each shaft bore); the holes are split between them
    and spread evenly around the circumference at each station, with the two
    stations offset 90° so opposing holes never share an axis. The same rule drives
    both the geometry and the reported ``placement_strategy`` so they always agree.
    """
    if count <= 0:
        return []
    z_stations = [length * 0.72, length * 0.28]   # over bore A, over bore B
    per = [(count + 1) // 2, count // 2]           # top gets the extra odd hole
    out: list[tuple[float, float]] = []
    for si, (z, n) in enumerate(zip(z_stations, per)):
        for k in range(n):
            ang = 90.0 * si + (360.0 / n) * k
            out.append((z, ang % 360.0))
    return out


class ShaftCouplerTemplate(BaseTemplate):
    object_type = "shaft_coupler"
    name = "Rigid Shaft Coupler"
    description = "Cylindrical coupler, two coaxial bores, threaded radial set-screw holes."
    dimensions = [
        DimensionSpec("length", "Body length", 25.0, 5.0, 300.0),
        DimensionSpec("outer_diameter", "Outer diameter", 20.0, 5.0, 200.0),
        DimensionSpec("bore_1", "Bore A diameter (top)", 6.0, 1.0, 180.0),
        DimensionSpec("bore_2", "Bore B diameter (bottom)", 8.0, 1.0, 180.0),
        DimensionSpec("set_screw_diameter", "Set-screw nominal Ø", 4.0, 1.0, 20.0),
        DimensionSpec("set_screw_count", "Set-screw count", 2.0, 0.0, 8.0),
    ]

    def build(self, spec: DesignSpec) -> "cq.Workplane":
        r = self.resolve(spec)
        length = r["length"]
        od = r["outer_diameter"]
        b1 = r["bore_1"]
        b2 = r["bore_2"]
        ss = r["set_screw_diameter"]
        count = int(round(r["set_screw_count"]))
        if max(b1, b2) >= od:
            raise CadGenerationError(
                f"bore ({max(b1, b2)}mm) must be smaller than the OD ({od}mm)")

        mid = length / 2.0
        body = cq.Workplane("XY").circle(od / 2.0).extrude(length)
        # Bore A from the top down to the mid plane; bore B from the bottom up.
        body = body.faces(">Z").workplane().hole(b1, depth=length - mid)
        body = body.faces("<Z").workplane().hole(b2, depth=mid)

        if count <= 0:
            return body

        # Radial threaded set-screw seats: tap-drill (minor) core hole + cosmetic
        # thread-relief ring grooves out to the major diameter (visible thread).
        core_r = set_screw_tap_drill(ss) / 2.0
        major_r = ss / 2.0
        pitch = set_screw_pitch(ss)
        r_out = od / 2.0
        bore_r = max(b1, b2) / 2.0

        for z, ang in set_screw_hole_positions(count, length):
            d = Vector(math.cos(math.radians(ang)), math.sin(math.radians(ang)), 0.0)
            # Core hole all the way from the outer surface into the bore.
            core = cq.Solid.makeCylinder(core_r, od, Vector(0, 0, z), d)
            body = body.cut(cq.Workplane(obj=core))
            # Cosmetic thread rings, only in the SOLID mid-wall band (clear of the
            # outer surface and the bore breakthrough) so the mesh stays watertight.
            s = bore_r + max(0.8, pitch)
            while s < r_out - 0.8:
                c = Vector(d.x * s, d.y * s, z)
                ring = cq.Solid.makeCylinder(major_r, pitch * 0.5, c, d)
                body = body.cut(cq.Workplane(obj=ring))
                s += pitch
        return body
