"""Square nut (DIN 557 / DIN 562 style): a square prism with chamfered bore
lead-ins and a modeled internal ISO metric thread.

The internal thread reuses the shared engine (``app.cad.threads.cut_internal_thread``):
the thread is bounded between lead-in chamfers so the flat bearing faces stay
clean, and the geometry audit reconciles the thread representation. The square
width across flats follows the standard table for the nominal size.

LEGAL / SOURCING NOTE:
Generated by LunaiCAD's own parametric engine from public DIN/ISO data.
McMaster CAD files must not be scraped, cached, redistributed, or used as source
geometry unless LunaiCAD has explicit commercial permission.
"""
from __future__ import annotations

import cadquery as cq

from app.cad.base import BaseTemplate, CadGenerationError, DimensionSpec
from app.schemas.design_spec import DesignSpec

# DIN 557 square-nut width across flats (s) and height (m), mm, by nominal Ø.
SQUARE_NUT: dict[float, dict[str, float]] = {
    5.0: {"s": 8.0, "m": 4.0}, 6.0: {"s": 10.0, "m": 5.0}, 8.0: {"s": 13.0, "m": 6.5},
    10.0: {"s": 17.0, "m": 8.0}, 12.0: {"s": 19.0, "m": 10.0}, 16.0: {"s": 24.0, "m": 13.0},
}


def square_nut_dims(nominal: float) -> dict[str, float]:
    row = SQUARE_NUT.get(round(nominal, 3))
    if row:
        return row
    return {"s": round(1.6 * nominal, 1), "m": round(0.85 * nominal, 1)}


class SquareNutTemplate(BaseTemplate):
    object_type = "square_nut"
    name = "Square Nut (DIN 557)"
    description = "Square prism with chamfered faces and a modeled internal thread."
    dimensions = [
        DimensionSpec("width", "Across-flats width", 19.0, 4.0, 90.0),
        DimensionSpec("height", "Nut height", 10.0, 1.0, 90.0),
        DimensionSpec("thread_major_diameter", "Thread major (nominal) diameter",
                      12.0, 2.0, 64.0),
        DimensionSpec("thread_pitch", "Thread pitch", 1.75, 0.2, 6.0),
    ]

    def build(self, spec: DesignSpec) -> "cq.Workplane":
        from app.cad.threads import cut_internal_thread
        from app.config import settings

        r = self.resolve(spec)
        w = r["width"]
        height = r["height"]
        major = r["thread_major_diameter"]
        pitch = r["thread_pitch"]
        if major >= w:
            raise CadGenerationError(
                f"thread major Ø ({major}mm) must be smaller than the square width ({w}mm)")

        body = cq.Workplane("XY").box(w, w, height, centered=(True, True, False))
        # Small edge chamfer on the top/bottom outer perimeter for a finished look.
        edge_ch = min(w * 0.06, height * 0.12)
        if edge_ch > 0.05:
            try:
                body = body.edges("|Z").chamfer(edge_ch)
            except Exception:  # noqa: BLE001
                pass

        detail = getattr(settings, "thread_detail", "modeled") or "modeled"
        body, _result = cut_internal_thread(
            body, major_diameter=major, pitch=pitch, length=height,
            z_bottom=0.0, detail=detail)
        return body
