"""Threaded rod / stud: a cylinder at the nominal (major) diameter with a modeled
external ISO metric thread along its length.

The thread is generated by the shared thread engine (``app.cad.threads``). For
short rods the thread is modeled (real helical geometry in STL + STEP); for long
rods, where a many-turn helical boolean is too slow/fragile, the engine returns a
clean chamfered cylinder marked ``failed_to_model_fallback_cosmetic`` and the
geometry audit reconciles the representation — a smooth rod is never reported as a
modeled thread.

LEGAL / SOURCING NOTE:
Generated by LunaiCAD's own parametric engine from public ISO metric thread data.
McMaster CAD files must not be scraped, cached, redistributed, or used as source
geometry unless LunaiCAD has explicit commercial permission.
"""
from __future__ import annotations

import cadquery as cq

from app.cad.base import BaseTemplate, DimensionSpec
from app.schemas.design_spec import DesignSpec


class ThreadedRodTemplate(BaseTemplate):
    object_type = "threaded_rod"
    name = "Threaded Rod / Stud"
    description = "Cylinder at the nominal diameter with a modeled external thread."
    dimensions = [
        DimensionSpec("thread_major_diameter", "Nominal (major) diameter", 12.0, 2.0, 64.0),
        DimensionSpec("thread_pitch", "Thread pitch", 1.75, 0.2, 8.0),
        DimensionSpec("length", "Rod length", 50.0, 4.0, 1000.0),
    ]

    def build(self, spec: DesignSpec) -> "cq.Workplane":
        from app.cad.threads import make_external_thread_rod
        from app.config import settings

        r = self.resolve(spec)
        detail = getattr(settings, "thread_detail", "modeled") or "modeled"
        rod, _result = make_external_thread_rod(
            major_diameter=r["thread_major_diameter"], pitch=r["thread_pitch"],
            length=r["length"], detail=detail)
        return rod
