"""GT2 timing-belt pulley: a pulley body with curved-root timing-belt tooth
grooves around its circumference (NOT involute spur-gear teeth) plus a central
bore and small flanges.

GT2 is a 2 mm-pitch belt profile. The pitch diameter is teeth × pitch / π. Tooth
grooves are approximated as rounded slots on the rim at the GT2 pitch — visibly a
timing pulley, distinct from a spur gear's pointed involute teeth. This is a
concept-accurate profile, not a certified GT2 tooth form.

LEGAL / SOURCING NOTE:
Generated by LunaiCAD's own parametric engine. McMaster CAD files must not be
scraped, cached, redistributed, or used as source geometry unless LunaiCAD has
explicit commercial permission.
"""
from __future__ import annotations

import math

import cadquery as cq

from app.cad.base import BaseTemplate, CadGenerationError, DimensionSpec
from app.schemas.design_spec import DesignSpec

GT2_PITCH_MM = 2.0
# GT2 tooth: ~0.75mm depth, rounded. Groove (the cut between belt teeth) radius.
_GT2_GROOVE_RADIUS = 0.55
_GT2_TOOTH_DEPTH = 0.76


class TimingPulleyGT2Template(BaseTemplate):
    object_type = "timing_pulley_gt2"
    name = "GT2 Timing Pulley"
    description = "Timing-belt pulley with GT2 (2mm pitch) tooth grooves and flanges."
    dimensions = [
        DimensionSpec("teeth", "Tooth count", 20.0, 6.0, 200.0),
        DimensionSpec("belt_width", "Belt width", 6.0, 2.0, 60.0),
        DimensionSpec("bore_diameter", "Bore diameter", 5.0, 1.0, 120.0),
        DimensionSpec("flange", "Flange (0 = none)", 1.0, 0.0, 6.0),
    ]

    def build(self, spec: DesignSpec) -> "cq.Workplane":
        r = self.resolve(spec)
        teeth = int(round(r["teeth"]))
        belt_w = r["belt_width"]
        bore = r["bore_diameter"]
        flange = r.dims_mm.get("flange", 0.0)

        pitch_d = teeth * GT2_PITCH_MM / math.pi
        pitch_r = pitch_d / 2.0
        # Outer radius sits just below the pitch line (belt teeth seat into grooves).
        outer_r = pitch_r - 0.254  # GT2 pitch-line differential ≈ 0.254mm
        if bore >= 2 * outer_r:
            raise CadGenerationError(
                f"bore ({bore}mm) too large for a {teeth}-tooth GT2 pulley "
                f"(Ø{2 * outer_r:.1f}mm)")

        body = cq.Workplane("XY").circle(outer_r).extrude(belt_w)

        # Cut GT2 tooth grooves: a rounded cutter at each tooth position on the rim,
        # swept the full belt width. Grooves (not pointed teeth) = a timing pulley.
        groove_center_r = outer_r + _GT2_GROOVE_RADIUS - _GT2_TOOTH_DEPTH
        cutters = None
        for i in range(teeth):
            ang = 2 * math.pi * i / teeth
            cx = groove_center_r * math.cos(ang)
            cy = groove_center_r * math.sin(ang)
            slot = (cq.Workplane("XY").center(cx, cy)
                    .circle(_GT2_GROOVE_RADIUS).extrude(belt_w))
            cutters = slot if cutters is None else cutters.union(slot)
        if cutters is not None:
            body = body.cut(cutters)

        # Optional flanges (thin discs above & below the toothed rim).
        if flange and flange > 0.05:
            fr = outer_r + 1.2
            top = cq.Workplane("XY").workplane(offset=belt_w).circle(fr).extrude(flange)
            bot = cq.Workplane("XY").workplane(offset=-flange).circle(fr).extrude(flange)
            body = body.union(top).union(bot)

        # Central bore through the whole stack.
        body = body.faces(">Z").workplane().hole(bore)
        return body
