"""Reusable modeled-thread engine.

Generates REAL helical thread geometry with the CAD kernel (not just metadata or
a cosmetic smooth bore). The geometry is present in both STL and STEP exports.

Representation values (single source of truth):
  * ``modeled``                          — real helical thread geometry is present
  * ``cosmetic``                         — deliberately a smooth bore (fast preview)
  * ``failed_to_model_fallback_cosmetic`` — modeling was attempted but the kernel
                                            could not produce a valid watertight
                                            solid, so we fell back to a smooth bore

LEGAL / SOURCING NOTE:
This thread geometry is generated by LunaiCAD's own parametric engine from public
ISO metric thread definitions. McMaster CAD files must not be scraped, cached,
redistributed, or used as source geometry unless LunaiCAD has explicit commercial
permission.
"""
from __future__ import annotations

from app.cad.threads.metric import (
    THREAD_COSMETIC,
    THREAD_FALLBACK,
    THREAD_MODELED,
    ThreadResult,
    cut_internal_thread,
    external_minor_diameter,
    internal_minor_diameter,
    make_external_thread_rod,
    metric_coarse_pitch,
)

__all__ = [
    "THREAD_MODELED",
    "THREAD_COSMETIC",
    "THREAD_FALLBACK",
    "ThreadResult",
    "cut_internal_thread",
    "make_external_thread_rod",
    "internal_minor_diameter",
    "external_minor_diameter",
    "metric_coarse_pitch",
]
