"""initial schema

Baseline migration: the full schema as defined by app/models.py at this revision
(users, projects, designs, export_files, feedback, manufacturing_checks, with
their indexes + foreign keys). This is the single source of truth for creating
the database in staging/production. For an EXISTING database that already has
these tables (created historically by create_all), run `alembic stamp head`
instead of `upgrade` so no data is touched.

Revision ID: 7fbf0c6446aa
Revises:
Create Date: 2026-06-19 16:03:09.609682
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fbf0c6446aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('designs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('spec_json', sa.JSON(), nullable=True),
    sa.Column('assumptions', sa.JSON(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('clarification_question', sa.Text(), nullable=True),
    sa.Column('missing_required', sa.JSON(), nullable=True),
    sa.Column('can_generate_with_defaults', sa.Boolean(), nullable=False),
    sa.Column('clarified_spec_candidate', sa.JSON(), nullable=True),
    sa.Column('route', sa.String(length=32), nullable=True),
    sa.Column('route_reason', sa.Text(), nullable=True),
    sa.Column('auto_repaired', sa.Boolean(), nullable=False),
    sa.Column('export_formats', sa.JSON(), nullable=True),
    sa.Column('program_code', sa.Text(), nullable=True),
    sa.Column('semantic_json', sa.JSON(), nullable=True),
    sa.Column('repair_attempts', sa.Integer(), nullable=False),
    sa.Column('preview_json', sa.JSON(), nullable=True),
    sa.Column('features_json', sa.JSON(), nullable=True),
    sa.Column('bounding_box', sa.JSON(), nullable=True),
    sa.Column('spec_hash', sa.String(length=32), nullable=True),
    sa.Column('thumbnail_key', sa.String(length=512), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('generation_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('export_files',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('design_id', sa.String(length=32), nullable=False),
    sa.Column('fmt', sa.String(length=16), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('design_id', sa.String(length=32), nullable=False),
    sa.Column('rating', sa.String(length=8), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('spec_hash', sa.String(length=32), nullable=True),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_design_id'), ['design_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_user_id'), ['user_id'], unique=False)

    op.create_table('manufacturing_checks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('design_id', sa.String(length=32), nullable=False),
    sa.Column('check', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manufacturing_checks')
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_design_id'))

    op.drop_table('feedback')
    op.drop_table('export_files')
    op.drop_table('designs')
    op.drop_table('projects')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
